"""other Migration

Revision ID: 47a0e9a89b25
Revises: 67055fffd138
Create Date: 2026-02-16 12:53:39.340807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a0e9a89b25'
down_revision: Union[str, Sequence[str], None] = '67055fffd138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('unit_price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'cart', 'users', ['user'], ['id'])
    op.drop_column('cart', 'Amount')
    op.drop_column('cart', 'ID')
    op.drop_column('cart', 'Unit_price')
    op.add_column('orders', sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('payment', sa.String(), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'User_Id')
    op.drop_column('orders', 'ID_Order')
    op.drop_column('orders', 'Payment')
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'Street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'City',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'City',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'Street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'active')
    op.drop_column('users', 'admin')
    op.add_column('orders', sa.Column('Payment', sa.VARCHAR(), nullable=False))
    op.add_column('orders', sa.Column('ID_Order', sa.INTEGER(), nullable=False))
    op.add_column('orders', sa.Column('User_Id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['User_Id'], ['id'])
    op.drop_column('orders', 'payment')
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'id_order')
    op.add_column('cart', sa.Column('Unit_price', sa.FLOAT(), nullable=True))
    op.add_column('cart', sa.Column('ID', sa.INTEGER(), nullable=False))
    op.add_column('cart', sa.Column('Amount', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'unit_price')
    op.drop_column('cart', 'amount')
    # ### end Alembic commands ###
