"""Initial Migration

Revision ID: 67055fffd138
Revises: 
Create Date: 2026-01-24 14:57:26.811283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67055fffd138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Product', sa.String(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('Unit_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('products',
    sa.Column('Product_Code', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Stock', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Product_Code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('Street', sa.String(), nullable=False),
    sa.Column('City', sa.String(), nullable=False),
    sa.Column('Province', sa.String(), nullable=False),
    sa.Column('Phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('orders',
    sa.Column('ID_Order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('Status', sa.String(), nullable=False),
    sa.Column('Payment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ID_Order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('cart')
    # ### end Alembic commands ###
