"""Second Migration

Revision ID: 7aba2cc6a14f
Revises: a8394f93fc3d
Create Date: 2026-02-21 11:02:11.184053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aba2cc6a14f'
down_revision: Union[str, Sequence[str], None] = 'a8394f93fc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'amount')
    # ### end Alembic commands ###
