"""OTHER Migration

Revision ID: f8ea37a1d672
Revises: 7aba2cc6a14f
Create Date: 2026-02-27 15:24:23.049541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ea37a1d672'
down_revision: Union[str, Sequence[str], None] = '7aba2cc6a14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'id_product')
    op.drop_column('cart', 'Product')
    op.drop_column('cart', 'product_id')
    op.add_column('orders', sa.Column('freight', sa.Float(), nullable=False))
    op.drop_column('orders', 'payment')
    op.drop_column('products', 'Category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Category', sa.VARCHAR(), nullable=False))
    op.add_column('orders', sa.Column('payment', sa.VARCHAR(), nullable=False))
    op.drop_column('orders', 'freight')
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), nullable=True))
    op.add_column('cart', sa.Column('Product', sa.VARCHAR(), nullable=True))
    op.add_column('cart', sa.Column('id_product', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
